version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd123"
      MSSQL_PID: "Express"
    ports: [1433:1433]

  zipkin:
    image: openzipkin/zipkin:latest
    ports: [9411:9411]

  prometheus:
    image: prom/prometheus:latest
    ports: [9090:9090]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"   # ЦЯ СТРОЧКА ОБОВ'ЯЗКОВА!
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports: [3000:3000]
    depends_on: [prometheus]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: [9200:9200]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports: [5601:5601]
    depends_on: [elasticsearch]