global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'study-tests'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true   # ігноруємо самопідписаний сертифікат